# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = pd.read_csv(url, sep="\t")

### Step 4. How many products cost more than $10.00?

In [4]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "", regex=False).astype(float)
chipo["product_price"] = chipo["item_price"] / chipo["quantity"]

In [5]:
chipo[chipo["product_price"] > 10].drop_duplicates(["item_name", "choice_description"]).shape[0]

707

In [6]:
# Alternate way: Create a new column with product plus choice variant
chipo["product_with_choice"] = chipo["item_name"] + " : " + chipo["choice_description"]
chipo[chipo["product_price"] > 10]["product_with_choice"].nunique()

707

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [7]:
chipo[["item_name", "choice_description", "product_price"]].drop_duplicates().sort_values(by=["item_name", "product_price"])

# I think the author's solution is wrong. It operates on the filtered table with price > $10

,item_name,choice_description,product_price
298,6 Pack Soft Drink,[Sprite],6.49
341,6 Pack Soft Drink,[Diet Coke],6.49
357,6 Pack Soft Drink,[Coke],6.49
721,6 Pack Soft Drink,[Nestea],6.49
3141,6 Pack Soft Drink,[Lemonade],6.49
...,...,...,...
3889,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
781,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2384,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
738,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

### Step 6. Sort by the name of the item

In [8]:
chipo.item_name.sort_values()

# OR

chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price,product_price,product_with_choice
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49,6 Pack Soft Drink : [Diet Coke]
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6 Pack Soft Drink : [Diet Coke]
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49,6 Pack Soft Drink : [Coke]
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6 Pack Soft Drink : [Diet Coke]
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49,6 Pack Soft Drink : [Coke]
...,...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75,"Veggie Soft Tacos : [Roasted Chili Corn Salsa,..."
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75,"Veggie Soft Tacos : [Fresh Tomato Salsa, [Blac..."
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49,Veggie Soft Tacos : [Roasted Chili Corn Salsa ...
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25,"Veggie Soft Tacos : [Fresh Tomato Salsa, [Faji..."
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49,Veggie Soft Tacos : [Fresh Tomato Salsa (Mild)...

### Step 7. What was the quantity of the most expensive item ordered?

In [9]:
chipo.loc[chipo["item_price"].idxmax()]["quantity"]

np.int64(15)

In [10]:
# Alternate, more robust
chipo.loc[chipo.item_price == chipo.item_price.max()]["quantity"]

3598    15
Name: quantity, dtype: int64

Note: The solution provided by the author uses `idxmax` which does not give multiple rows in case of ties. The solution I mentioned as **Alternate** seems to be more robust. <br> For this particular dataset and query, this does not matter, but readers can do a quick check by comparing results using `idxmin` and `chipo.item_price == chipo.item_price.min()` and see the difference 🙂

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [11]:
chipo[chipo["item_name"] == "Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [12]:
chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)].shape[0]

20